### PR TITLE
Update workflow trigger

### LINKED ISSUE #3: Use `Knip` as `Jest` workflow trigger
Jest workflow is being triggered after `Build` which doesn't exist and it should trigger on `Knip` completion.

### PR DESCRIPTION
**Pull request by Keyrxng**
Resolves #3

### CODE REVIEW

**Comment by Keyrxng** [comment]
CI is going to be an issue in this repo I think

**Comment by Keyrxng** [comment]
@gentlementlegen should I also include the changes to `worker.ts` regarding `JSON.parse` or open another issue and PR?

**Comment by gentlementlegen** [comment]
Would be nice to have in this one, but you can do it separately if you prefer. Since it's a one line PR it could fit here easily.

**Review by gentlementlegen — APPROVED** [review]

**Review by gentlementlegen — CHANGES_REQUESTED** [review]
I am not sure if this was changed on another PR, but Knip should run on `pull_request` not `pull_request_target`

**Comment by Keyrxng** [comment]
@gentlementlegen I hadn't pulled but we should be good now

**Review by gentlementlegen — APPROVED** [review]

**Pull request merged**
